In [3]:
!pip install stable-baselines3

Defaulting to user installation because normal site-packages is not writeable
  Using cached stable_baselines3-2.2.1-py3-none-any.whl (181 kB)



[notice] A new release of pip is available: 23.1.2 -> 23.3.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [20]:
import random
import numpy as np
import tqdm
import torch

from game import Game, Move, Player
from Agent import PPOAgent
from QuixoEnv import QuixoEnv
from ActionDecoder import ActionDecoder
from StateEncoder import StateEncoder


g = Game()
b = g.get_board()

me_player = "models/checkpoints_selfplay/ppo_last_selfplay.ai"
p1 = PPOAgent(me_player)

state = p1.state_encoder(b, 0)
policy = p1.model.policy
policy(torch.Tensor(state, deterministic=True).cuda())


Wrapping the env with a `Monitor` wrapper
Wrapping the env in a DummyVecEnv.


(tensor([17], device='cuda:0'),
 tensor([[5.6430]], device='cuda:0', grad_fn=<AddmmBackward0>),
 tensor([-0.7942], device='cuda:0', grad_fn=<SqueezeBackward1>))

In [155]:
env = QuixoEnv()
ad = ActionDecoder()
print(env.adversary_first)
print(env._get_state())

print("="*20)
obs, _, done, _, _ = env.step(10)
print(f"{done=}")
print(ad(10))
print(obs)

print("="*20)
obs, _, done, _, _ = env.step(32)
print(f"{done=}")
print(ad(32))
print(obs)


True
[[[ 0  0  0  0  0]
  [ 0  0  0  0  0]
  [ 0  0  0  0  0]
  [ 0  0  0  0  0]
  [-1  0  0  0  0]]]
done=False
((0, 3), <Move.RIGHT: 3>)
[[[ 0  0  0 -1  0]
  [ 0  0  0  0  0]
  [ 0  0  0  0  0]
  [ 0  0  0  0  1]
  [-1  0  0  0  0]]]
done=False
((4, 0), <Move.LEFT: 2>)
[[[ 1  0  0 -1 -1]
  [ 0  0  0  0  0]
  [ 0  0  0  0  0]
  [ 0  0  0  0  1]
  [-1  0  0  0  0]]]
